### ISSUE TITLE
MovieClipEntity:removeChild does not work when passing [MovieClipEntity].entity

### ISSUE THREAD

**Issue by samueldr** [anhero/BaconBox#1]
When doing:

```
movieclips:removeChild(aMovieClip.entity)
```

I get:

```
Error: Can't return an entity in LuaHelper::getEntityFromLuaEntity.
```

Though, using:

```
movieclips:removeChild(aMovieClip)
```

Is perfectly [cromulent](https://en.wiktionary.org/wiki/cromulent) with BaconBox.

**Comment by JoeDupuis** [comment]
In the example aMovieClip is a LuaEntity and the aMovieClip.entity field   is a MovieClipEntity UserData
